name: Deploy

env:

  ARTIFACTORY_USERNAME : ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD : ${{ secrets.ARTIFACTORY_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup and Deploy

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Deploy Social Hub
        run: |
          cd $GITHUB_WORKSPACE
          export ROOT_DIR=$GITHUB_WORKSPACE
          ./gradlew publish